import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          min-h-screen bg-animated-gradient flex items-center justify-center p-4
        `}
      >    
          <div
            className="absolute inset-0 bg-cover bg-center"
            style={{
              backgroundImage: "url('/bg5.jpg')", 
              opacity: 0.3, 
              zIndex: -2,
            }}
          ></div>
          <div className="absolute inset-0 overflow-hidden">
              {/* Animated background elements */}
              <div className="absolute top-10 left-20 w-32 h-32 rounded-full bg-white/10 ipulse" style={{ animationDelay: '0s' }}></div>
              <div className="absolute top-2/3 right-1/4 w-24 h-24 rounded-full bg-white/10 ipulse" style={{ animationDelay: '3s' }}></div>
              <div className="absolute bottom-20 left-1/4 w-20 h-20 rounded-full bg-white/10 ipulse" style={{ animationDelay: '5s' }}></div>
              <div className="absolute top-1/4 right-20 w-12 h-12 rounded-full bg-white/10 ipulse" style={{ animationDelay: '8s' }}></div>
          </div>

          <div className="w-1/2 bg-white/60 backdrop-blur-lg rounded-sm shadow-2xl overflow-hidden transition-all duration-300 hover:shadow-3xl">
            {children}
          </div>          
          <div className="absolute bottom-10 left-0 right-0 text-center">
            <p className="text-white/50 text-sm">Don't have an account?
              <a href="#" className="text-white hover:underline">Sign up</a>
            </p>
          </div>
      </body>
    </html>
  );
}
