import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import AnimatedBg from './ui/AnimatedBg/AnimatedBg';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden
          flex flex-col items-center
        `}
      >
        <AnimatedBg />
        <div className="w-full mins-w-screen grow sm:p-10 md:p-25 lg:p-25 relative z-10">
          {children}
        </div>
        <div className="text-center p-5">
          <p className="text-white/50 text-sm">Don't have an account?
            <a href="#" className="text-white hover:underline">Sign up</a>
          </p>
        </div>
      </body>
    </html>
  );
}
